services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./server/.env.docker
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB -h localhost']
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  server:
    build: ./server
    restart: always
    env_file:
      - ./server/.env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'

  client:
    build: ./client
    restart: always
    ports:
      - '5173:80'

volumes:
  pgdata:
